# Generated by Django 5.1.6 on 2025-02-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seyali', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
