# Generated by Django 5.1.6 on 2025-03-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seyali', '0003_question_choice_quiz_question_quiz_useranswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='answered_at',
        ),
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.TextField(default='Default description'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
