# Generated by Django 5.1.6 on 2025-03-02 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seyali', '0004_remove_quiz_created_by_remove_useranswer_answered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='quiz',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seyali.quiz'),
        ),
    ]
